"""rename password to password_hash

Revision ID: 08a040db9eea
Revises: 867f92e8fa73
Create Date: 2026-04-23 09:33:12.954054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a040db9eea'
down_revision: Union[str, None] = '867f92e8fa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """テーブルの作成・カラムの追加などの変更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False, comment='ハッシュ化されたパスワード'))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """upgrade()の変更を元に戻す"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False, comment='ハッシュ化されたパスワード'))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
