"""add profile columns to users

Revision ID: 32c2d179646b
Revises: 59872208f0b8
Create Date: 2026-05-12 02:41:03.386343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c2d179646b'
down_revision: Union[str, None] = '59872208f0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """テーブルの作成・カラムの追加などの変更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('grade', sa.Integer(), nullable=True, comment='学年（1〜4）'))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True, comment='学科'))
    op.add_column('users', sa.Column('course', sa.String(), nullable=True, comment='コース'))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True, comment='自己紹介'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """upgrade()の変更を元に戻す"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'course')
    op.drop_column('users', 'department')
    op.drop_column('users', 'grade')
    # ### end Alembic commands ###
