"""add parent_id to comment tables

Revision ID: 867f92e8fa73
Revises: 8f178821ae5d
Create Date: 2026-04-23 04:25:51.051192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867f92e8fa73'
down_revision: Union[str, None] = '8f178821ae5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """テーブルの作成・カラムの追加などの変更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_comments', sa.Column('parent_id', sa.Integer(), nullable=True, comment='返信先コメントID（NULLなら記事への直接コメント）'))
    op.create_foreign_key(None, 'article_comments', 'article_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('question_comments', sa.Column('parent_id', sa.Integer(), nullable=True, comment='返信先コメントID（NULLなら質問への直接コメント）'))
    op.create_foreign_key(None, 'question_comments', 'question_comments', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """upgrade()の変更を元に戻す"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_comments', type_='foreignkey')
    op.drop_column('question_comments', 'parent_id')
    op.drop_constraint(None, 'article_comments', type_='foreignkey')
    op.drop_column('article_comments', 'parent_id')
    # ### end Alembic commands ###
