"""add bio to users

Revision ID: 9f528050ceeb
Revises: 59872208f0b8
Create Date: 2026-05-13 05:45:32.257539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f528050ceeb'
down_revision: Union[str, None] = '59872208f0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """テーブルの作成・カラムの追加などの変更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True, comment='自己紹介'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """upgrade()の変更を元に戻す"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
