"""remove unused profile columns

Revision ID: a93a2b0aeaca
Revises: 32c2d179646b
Create Date: 2026-05-12 04:52:37.554955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93a2b0aeaca'
down_revision: Union[str, None] = '32c2d179646b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """テーブルの作成・カラムの追加などの変更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'grade')
    op.drop_column('users', 'course')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """upgrade()の変更を元に戻す"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True, comment='学科'))
    op.add_column('users', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=True, comment='コース'))
    op.add_column('users', sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True, comment='学年（1〜4）'))
    # ### end Alembic commands ###
